### ISSUE TITLE
Güncel: veri çekilmiyor

### ISSUE THREAD

**Issue by eminkaplan** [emreuenal/turkiye-il-ilce-sokak-mahalle-veri-tabani#7]
Traceback (most recent call last):
  File "/root/nvi/turkiye-il-ilce-sokak-mahalle-veri-tabani/crawler.py", line 70, in <module>
    request_verification_token_cookie = r.cookies['__RequestVerificationToken']
  File "/usr/lib/python3.10/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3.10/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='__RequestVerificationToken', domain=None, path=None"

Şeklinde hata döndürüyor.
Müsait olduğunuzda kontrol edebilir misiniz hocam ?

**Comment by battincik** [comment]
Sanırsam verileri çektiği siteye captcha eklemişler ondan dolayı olabilir

**Comment by ennettakip** [comment]
@emreuenal  bey destek olursa bu sorun çözülür captcha  dan kaynaklıysa eğer

**Comment by ramazansancar** [comment]
reCAPTCHA eklendiği için çekilemez
